CREATE DATABASE  IF NOT EXISTS `JustRecipes`;
USE `JustRecipes`;

DROP TABLE IF EXISTS `USER_ACCINFOTYPE`;
CREATE TABLE `USER_ACCINFOTYPE` (
  `ACCINFOTYPEID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCINFOTYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ACCINFOTYPEID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `USER_ACCINFO`;
CREATE TABLE `USER_ACCINFO` (
  `ACCINFOID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCINFOTYPEID` int(11) DEFAULT NULL,
  `USERID` int(11) DEFAULT NULL,
  `AUTHORITY` varchar(255) DEFAULT 'ROLE_USER',
  PRIMARY KEY (`ACCINFOID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TBL_USER_BASIC`;
CREATE TABLE `TBL_USER_BASIC` (
  `USERID` int(11) NOT NULL AUTO_INCREMENT,
  `SYSTEMID` int(11) DEFAULT NULL,
  `FNAME` varchar(45) DEFAULT NULL,
  `LNAME` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(45) DEFAULT NULL,
  `USERCODE` varchar(45) DEFAULT NULL,
  `CANLOGIN` smallint(1) DEFAULT '1',
  `APITOKEN` varchar(80) NOT NULL DEFAULT 'test',
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TBL_USER_SESSIONS`;
CREATE TABLE `TBL_USER_SESSIONS` (
  `SESSION_ID` varchar(100) NOT NULL,
  `VALID_SESSION` char(1) NOT NULL,
  `MAX_INACTIVE` int(11) NOT NULL,
  `LAST_ACCESS` bigint(20) NOT NULL,
  `APP_NAME` varchar(255) DEFAULT NULL,
  `SESSION_DATA` mediumblob,
  PRIMARY KEY (`SESSION_ID`),
  KEY `KAPP_NAME` (`APP_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `JUSTRECIPES`.`USER_ACCINFOTYPE` (`ACCINFOTYPE`) VALUES ('User');
INSERT INTO `JUSTRECIPES`.`USER_ACCINFOTYPE` (`ACCINFOTYPE`) VALUES ('Admin');

INSERT INTO `JUSTRECIPES`.`TBL_USER_BASIC` (`SYSTEMID`, `FNAME`, `LNAME`, `PASSWORD`, `USERCODE`, `CANLOGIN`, `APITOKEN`) VALUES ('1', 'test', 'test', SHA1('test'), 'test', '1', 'test');

INSERT INTO `JUSTRECIPES`.`USER_ACCINFO` (`ACCINFOTYPEID`, `USERID`, `AUTHORITY`) VALUES ('1', '1', 'ROLE_USER');
